name: nate22233-t3
main: com.tenjava.entries.nate22233.t3.TenJava
version: '${project.version}'

commands:
    event:
        usage: /<command>
        description: The main event command!
        
permissions:
    randomevents.command:
        default: op